# Gender and age


**Input**

-   DemographyGunOwners/data/clean/gs-gun-owners.rds

**Output**

-   DemographyGunOwners/output

**Last ran**

-   `r format(Sys.Date(), format = "%A, %B %d, %Y")`

```{r,  message = FALSE, warning = FALSE}
packages <-
  c(
    "tidyverse",
    "purrr",
    "haven",
    "survey",
    "tidyr",
    "gtsummary",
    "janitor",
    "dplyr",
    "here",
    "vtable",
    "paletteer",
    "fastDummies",
    "ggpubr",
    "viridis"
  )

pacman::p_load(
  packages,
  character.only = TRUE
)
```

## Import data

```{r}
gun <-
  read_rds(
     here(
      path_od, 
      "data",
      "clean",
      "gs-gun-owners.rds"
      )
  )
```

## Bar chart



```{r}
df <-
  gun %>% 
  group_by(year, gender, age4) %>% 
  mutate(tot = sum(weight)) %>% 
  group_by(year, gender, age4, racethnicity) %>% 
  reframe(
    pct = round(sum(weight, na.rm = T)/tot, 4),
    n = n()
    ) %>% 
  distinct(year, gender, age4, racethnicity, pct, n)
``` 

```{r}
plots <-
  map(
    c(2013, 2025),
    ~ {
      
      p <-
        df %>%  
        filter(year == .x, gender != "Other") %>% 
        ggplot(
          aes(
          x = gender,
          y = pct,
          fill =  racethnicity
        )) +
        geom_col(
          show.legend = TRUE
          ) +
        facet_grid(
          cols = vars(age4),
          scales = "free_x",
          switch = "x"
          ) +
          scale_fill_viridis_d(
            direction = 1,
            end = 0.6,
            drop = F,
            labels = 
              function(x) 
                str_wrap(x, width = 7)
        ) +
        theme +
        theme(
          strip.placement = "outside",
          strip.background = element_rect(
            fill = "white",
            color = "white"
          ),
          strip.text =
            element_text(
              size = 13
            ),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.ticks.x = element_blank(),
          legend.title = element_blank(),
          legend.text = 
            element_text(
              size = 8
            ),
          text = element_text(
            size = 12
          ),
          axis.text.x  = element_text(
            face = "italic"
          ),
          plot.title =
            element_text(
              hjust = 0.5,
              size = 14
            )
        ) +
        scale_y_continuous(
          label = scales::percent,
          breaks = seq(0, 1, by = .25)
        ) +
        guides(fill = guide_legend(nrow = 1)) +
        labs(
          x = "",
          y = "",
          title = ""
        ) 
      }
    )
```


Combine plots from 2013 and 2025.

```{r}
p <- 
  ggarrange(
    plots[[1]] +
      labs(
        title = "(a) 2013"
      ),
    plots[[2]] +
      labs(
        x = "Age, in years",
        title = "(b) 2025"
      ),
    common.legend = TRUE,
    ncol = 1
    )

ggsave(
  height = 8,
  width = 6, 
  here(
    path_ol, 
    "figures/gender-race-year.jpeg"
  ),
  p
)
```

Save 2 plots to use as panels in overleaf

```{r}
ggsave(
  height = 4,
  width = 7, 
  here(
    path_ol, 
    "figures/gender-race-2013.jpeg"
  ),
  plots[[1]] +
    labs(caption = "") +
    theme(legend.position = "top")
    )

 ggsave(
    height = 4,
    width = 7, 
    here(
      path_ol, 
      "figures/gender-race-2025.jpeg"
    ),
    plots[[2]] +
      labs(title = "", x = "Age, in years") +
      guides(fill = "none")
      )
```

## Estimates with CIs

```{r}
des <- svydesign(
  ids = ~1,          # no clustering info
  weights = ~weight,
  data = gun
)

gender <- 
  svyby(
    ~gender,
    ~year,
    des,
    svymean,
    vartype = c("se", "ci"),
    level = 0.95
    ) %>% 
  clean_names() %>% 
  mutate(across(-year, ~ .x * 100))


long <-
  gender %>%
  pivot_longer(
    cols = -year,
    names_to = "name",
    values_to = "value"
  ) %>%
  mutate(
    stat = case_when(
      str_starts(name, "se_")   ~ "se",
      str_starts(name, "ci_l_") ~ "ci_l",
      str_starts(name, "ci_u_") ~ "ci_u",
      TRUE                      ~ "pct"
    ),
    group = name %>%
      str_remove("^se_") %>%
      str_remove("^ci_l_") %>%
      str_remove("^ci_u_")
  ) %>%
  select(year, group, stat, value) %>%
  pivot_wider(
    names_from = stat,
    values_from = value
  ) %>% 
   mutate(
    gender = 
      case_when(
        str_detect(group, "female") ~ 2,
        str_detect(group, "male") ~ 1,
        TRUE ~ 3) %>% 
      factor(
        levels = 1:3, 
        labels = 
          c("Male", "Female", "Other")
        ),
    # lower CI at least 0
    ci_l = ifelse(ci_l < 0, 0, ci_l)
  ) %>% 
  filter(!is.na(pct)) 
```


## Gun ownership by political party


```{r}
cap <-
  paste0(
    "This figure plots percent of U.S. gun-owner adults (N=",
     nrow(gun),") stratified by gender ",
     "from seven waves of the National ",
    "Survey of Gun Policy, spanning 2013 to 2025. Individuals who do not ",
    "identify as male or female are not included in this figure. "
  )
```


```{r}
long %>% 
  filter(gender != "Other") %>% 
  mutate(year = factor(year)) %>%  
  ggplot(
    aes(x = year, y = pct, group = gender, color = gender, fill = gender)
  ) +
  geom_col() +
  theme +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    legend.background = element_blank(),
    legend.key = element_blank(),
    legend.text = element_text(size = 8),
    legend.title = element_text(size = 10, hjust = .5)
  ) +
  guides(color = "none") +
  scale_color_paletteer_d("MoMAColors::Althoff") +
  scale_fill_paletteer_d("MoMAColors::Althoff") +
  labs(
    x = "Survey Year",
    y = "Percent of U.S. gun owners",
    fill = "Gender"
  ) 

ggsave(
  height = 6,
  width = 8, 
  here(
    path_ol, 
    "figures/gender.jpeg"
  )
)
```