# Gender

This chapter focuses time trends in gender


**Input**

-   DemographyGunOwners/data/clean/gs-gun-owners.rds

**Output**

-   DemographyGunOwners/output

**Last ran**

-   `r format(Sys.Date(), format = "%A, %B %d, %Y")`
```{r,  message = FALSE, warning = FALSE}
packages <-
  c(
    "tidyverse",
    "purrr",
    "haven",
    "survey",
    "tidyr",
    "gtsummary",
    "janitor",
    "dplyr",
    "here",
    "vtable",
    "paletteer",
    "fastDummies"
  )

pacman::p_load(
  packages,
  character.only = TRUE
)
```

## Import data

```{r}
gun <-
  read_rds(
     here(
      path_od, 
      "data",
      "clean",
      "gs-gun-owners.rds"
      )
  )
```


## Estimates with CIs

```{r}
gun %>% tabyl(gender)
```

```{r}
des <- svydesign(
  ids = ~1,          # no clustering info
  weights = ~weight,
  data = gun
)

gender <- 
  svyby(
    ~gender,
    ~year,
    des,
    svymean,
    vartype = c("se", "ci"),
    level = 0.95
    ) %>% 
  clean_names() %>% 
  mutate(across(-year, ~ .x * 100))


long <-
  gender %>%
  pivot_longer(
    cols = -year,
    names_to = "name",
    values_to = "value"
  ) %>%
  mutate(
    stat = case_when(
      str_starts(name, "se_")   ~ "se",
      str_starts(name, "ci_l_") ~ "ci_l",
      str_starts(name, "ci_u_") ~ "ci_u",
      TRUE                      ~ "pct"
    ),
    group = name %>%
      str_remove("^se_") %>%
      str_remove("^ci_l_") %>%
      str_remove("^ci_u_")
  ) %>%
  select(year, group, stat, value) %>%
  pivot_wider(
    names_from = stat,
    values_from = value
  ) %>% 
   mutate(
    gender = 
      case_when(
        str_detect(group, "female") ~ 2,
        str_detect(group, "male") ~ 1,
        TRUE ~ 3) %>% 
      factor(
        levels = 1:3, 
        labels = 
          c("Male", "Female", "Other")
        ),
    # lower CI at least 0
    ci_l = ifelse(ci_l < 0, 0, ci_l)
  ) %>% 
  filter(!is.na(pct)) 
```


## Gun ownership by political party


```{r}
cap <-
  paste0(
    "This figure plots percent of U.S. gun-owner adults (N=",
     nrow(gun),") stratified by gender ",
     "from seven waves of the National ",
    "Survey of Gun Policy, spanning 2013 to 2025. Individuals who do not ",
    "identify as male or female are not included in this figure. "
  )
```


```{r}
long %>% 
  filter(gender != "Other") %>% 
  mutate(year = factor(year)) %>%  
  ggplot(
    aes(x = year, y = pct, group = gender, color = gender, fill = gender)
  ) +
  geom_col() +
  theme +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    legend.background = element_blank(),
    legend.key = element_blank(),
    legend.text = element_text(size = 8),
    legend.title = element_text(size = 10, hjust = .5)
  ) +
  guides(color = "none") +
  scale_color_paletteer_d("MoMAColors::Althoff") +
  scale_fill_paletteer_d("MoMAColors::Althoff") +
  labs(
    x = "Survey Year",
    y = "Percent of U.S. gun owners",
    fill = "Gender"
  ) 

ggsave(
  height = 6,
  width = 8, 
  here(
    path_ol, 
    "figures/gender.jpeg"
  )
)
```