# Basic Demographics of Gun Owners

This chapter creates a descriptive table that shows the demographics of US 
gun owners from 2013 to 2025.

**Input**

-   DemographyGunOwners/data/clean/gs-gun-owners.rds

**Output**

-   DemographyGunOwners/output

**Last ran**

-   `r format(Sys.Date(), format = "%A, %B %d, %Y")`

```{r,  message = FALSE, warning = FALSE}
packages <-
  c(
    "tidyverse",
    "purrr",
    "haven",
    "survey",
    "tidyr",
    "gtsummary",
    "janitor",
    "dplyr",
    "here",
    "vtable"
  )

pacman::p_load(
  packages,
  character.only = TRUE
)
```

## Import data

```{r}
gun <-
  read_rds(
     here(
      path_od, 
      "data",
      "clean",
      "gs-gun-owners.rds"
      )
  )
```

## Demographic Table

```{r}
demovars <-
  c(
    "gender",
    "age4",
    "racethnicity",
    "party3",
    "educ5",
    "employ",
    "income4",
    "marital",
    "region4"
  )

summstats <-
  c("notNA(x)", "mean(x)")
summnames <-
  c("Observations", "Mean")
```

Solid table, not perfect but good enough to share with Cass.

```{r, results = "asis", warning = F, message = F}
st(
  gun,
  vars = demovars,
  group = "year",
  group.weights = "weight",
  summ = summstats,
  summ.names = summnames,
  title = "Demographic characteristics of US gun owners between 2013 and 2025",
  out = "latex",
  numformat = "comma",
  labels = T,
  file =  here(path_ol, "tables/gun-own-chars"),
  digits = 2,
  factor.counts = FALSE,
  anchor = "tab:GunOwnChars",
  fit.page = '\\textwidth'
  )
```


```{r}
nrow(gun)
```
