# Basic Demographics of Gun Owners

This chapter creates a descriptive table that shows the demographics of US 
gun owners from 2013 to 2025.

**Input**

-   DemographyGunOwners/data/clean/gs-gun-owners.rds

**Output**

-   DemographyGunOwners/output

**Last ran**

-   `r format(Sys.Date(), format = "%A, %B %d, %Y")`

```{r,  message = FALSE, warning = FALSE}
packages <-
  c(
    "tidyverse",
    "purrr",
    "haven",
    "survey",
    "tidyr",
    "gtsummary",
    "janitor",
    "dplyr",
    "here",
    "vtable"
  )

pacman::p_load(
  packages,
  character.only = TRUE
)
```

## Import data

```{r}
gun <-
  read_rds(
     here(
      path_od, 
      "data",
      "clean",
      "gs-gun-owners.rds"
      )
  )
```

## Demographic variables

```{r}
demovars <-
  c(
    "gender",
    "age4",
    "racethnicity",
    "party5",
    "nranow",
    "educ",
    "employ",
    "income4",
    "marital",
    "region4"
  )
```

## Tabulate values

```{r}
walk(demovars, ~ print(tabyl(gun, .x)))
```

## Full sample summary

```{r}
ds <- survey::svydesign(~ 1, data = gun, weights = ~ weight) 
```

```{r}
overview <-
  ds %>%
  tbl_svysummary(
    include = demovars,
    statistic = list(all_categorical() ~ "{p}%")
  )
```

```{r}
overview_tbl <-
  overview %>%
  modify_header(
    label ~ "Characteristic",
    all_stat_cols() ~ "Overall"
  ) %>%
  modify_table_body(
    ~ .x %>%
      filter(
        !(variable == "nranow" & label == "No"),
        ! grepl("Ques", label)
        ) %>%
      mutate(
        label = ifelse(
          row_type == "level",
          paste0("  ", label),
          label
        ),
         # replace 0% in 2025 to indicate question was not asked
         stat_0 = case_when(
           variable == "marital" & grepl("with", label) ~ ".",
           TRUE ~ stat_0
           )
      )
  ) %>%
  modify_footnote(all_stat_cols() ~ NA_character_) %>%
  as_kable_extra(
    format = "latex",
    booktabs = TRUE,
    escape = FALSE,
    caption = "Demographic Characteristics of U.S. Gun Owners",
    linesep = "",
    align = "lc",
    label = "Summary"
  ) %>%
  kable_styling(
    latex_options = c("HOLD_position", "scale_down"),
    font_size = 8
  ) %>%
  column_spec(1, width = "6cm") %>%
  column_spec(2, width = "2cm") %>% 
  footnote(
    number = 
      paste(
        "Values are weighted percentages",
        "describing the demographic composition of U.S.",
        "gun owners between 2013 and 2025.",
       "Due to differences in the survey questions",
        "over time, ``Some college or associates degree''",
        "also includes responses for vocational or technical schools."
        ),
    threeparttable = TRUE,
    escape = FALSE,
    fixed_small_size = T
  )

save_kable(
  overview_tbl,
  file = here(path_ol, "tables/summary.tex")
)
```


## Year

```{r}
year_tbl <-
  ds %>%
  tbl_svysummary(
    by = year,
    include = demovars,
    missing = "no",
    statistic = all_categorical() ~ "{p}%"
  ) %>%
  modify_header(
    label ~ "Characteristic",
    all_stat_cols() ~ "{level}"
  ) %>%
  modify_table_body(
    ~ {
      
      tbl <- .x
      
      # compute unweighted yearly totals
      counts <- format(table(nra$year), big.mark = ",")
      
      # create row with obs
      n_row <- tibble(
        variable = NA,
        var_label = NA,
        row_type = "label",
        label = "Observations",
        !!!setNames(
          as.list(counts),
          paste0("stat_", seq_along(counts))
          )
        ) %>% 
        mutate(across(starts_with("stat"), trimws)
          )

      bind_rows(n_row, tbl) %>%
        filter(! grepl("Ques", label)) %>% 
        mutate(
           label = ifelse(
            row_type == "level" & label != "Observations",
            paste0("  ", label),
            label),
          stat_2 = ifelse(
               variable == "party5" & row_type == "level",
               "-", stat_2
               ),
           across(
             c(stat_6, stat_7),
             ~ ifelse(
               variable == "marital" & grepl("with", label),
               "-", .x
               )
             )
           )
    }
  ) %>%
  modify_footnote(all_stat_cols() ~ NA_character_) %>%
  as_kable_extra(
    format = "latex",
    booktabs = TRUE,
    escape = FALSE,
    label = "SummaryYear",
    linesep = "",
    caption = "Demographic Characteristics of U.S. Gun Owners by Survey Year",
    align = "lccccccc"
  ) %>%
  kable_styling(
    latex_options =
      c("hold_position", "scale_down"),
   font_size = 9
  ) %>%
  column_spec(1, width = "4.5cm") %>%
  column_spec(
    2:8, 
    width = "1.3cm"
    ) %>% 
  row_spec(1, bold = TRUE) %>% 
  footnote(
   number = paste0(
    "Note: Values are weighted percentages describing ",
    "the demographic composition of U.S. gun owners by survey year. ",
    "Because survey question wording varied across waves, the category ",
    "``Some college or associate’s degree'' also includes respondents ",
    "reporting vocational or technical school."
  ),
    threeparttable = TRUE,
    escape = FALSE,
    fixed_small_size = TRUE
  )

save_kable(
  year_tbl,
  file = here(path_ol, "tables/summary-year.tex")
)
```


```{r}


```
