## 2021

[Gun center page on 2021 survey](https://publichealth.jhu.edu/2022/new-survey-finds-broad-public-support-for-policies-regulating-carrying-guns-in-public-in-the-us)

From the supplement of [Cass's paper on this survey](https://www.sciencedirect.com/science/article/pii/S0091743522003632?via%3Dihub): N = 2,778, Gun owner N=808,	Non-gun owner N=1,970.

[Public opinion on laws regulating public gun carrying](https://pmc.ncbi.nlm.nih.gov/articles/PMC11578283/) is 
another one of Cass' papers on this survey. This paper says 30% in 2021.

I am getting 29\%. Close enough!

```{r,  message = FALSE, warning = FALSE, echo = FALSE}
packages <-
  c(
    "tidyverse",
    "purrr",
    "haven",
    "tidyr",
    "janitor",
    "skimr",
    "psych",
    "kableExtra",
    "dplyr",
    "vtable",
    "here",
    "labelled"
  )

pacman::p_load(
  packages,
  character.only = TRUE
)
```

## Load data

```{r}
data <-
  read_rds(
   here(
    path_od, 
    "data",
    "clean",
    "gs-2021.rds"
    )
  )
```


## National prevalence

```{r}
data %>% tabyl(gunhomeper) %>% adorn_totals("row")
```

```{r}
data %>% 
  mutate(
    g = as.numeric(gunhomeper == "Yes")
  ) %>% 
  summarise(
    across(
      starts_with("weight"),
      ~ (sum(g*.x, na.rm = T)/sum(.x, na.rm = T))
    )
  )
```

```{r}
filter(data, is.na(weight2)) %>% nrow() == 0
```

```{r}
data %>% 
  filter(sample == "General population") %>% 
  mutate(
    g = as.numeric(gunhomeper == "Yes")
  ) %>% 
  summarise(
    across(
      c("weight1", "weight2"), 
      ~ sum(g*.x, na.rm = T)/sum(.x, na.rm = T)
    )
  )

```
