# Legalisation Dates

This chapter prepares the dataset, including constructing and standardizing the dates of sports betting legalization for each state.

```{r,  message = FALSE, warning = FALSE, echo = F}
packages <-
  c(
    "tidyverse",
    "purrr",
    "haven",
    "survey",
    "tidyr",
    "readxl",
    "janitor",
    "here"
  )

pacman::p_load(
  packages,
  character.only = TRUE
)
```

## Import data

Ben shared this document:
```{r}
dates <-
  read_excel(
     here(
      path_od, 
      "data",
      "raw",
      "sportsbettingdates.xlsx"
      ),
     sheet = "df"
  )
```

```{r}
dates %>% 
  sample_n(10) %>% 
  head(10) %>% 
  kbl(
    caption = 
      "Sports Betting Legalization Data",
    align = "c",
    format = "html",
    booktabs = TRUE
  ) %>% 
  kable_classic(
    full_width = FALSE,
    html_font = "Cambria"
    )  %>% 
  scroll_box(width = "800px", height = "500px")
```

## Tidy data

We convert the dates into the correct format and retrieve state name 
abbreviations.

```{r}
state_lookup <- setNames(state.abb, tolower(state.name))

clean <-
  dates %>% 
  rename(
    state_name = state
  ) %>% 
  mutate(
    across(
      ends_with("date"),
      ~excel_numeric_to_date(as.numeric(.x))
    ),
    state = state_lookup[tolower(trimws(state_name))]
  )
```

## Export data

```{r}
write_rds(
  clean,
  here(
    path_od, 
    "data",
    "clean",
    "sportsbettingdates.rds"
    )
) 
```

