# Create gun ownership panel

This chapter creates a state level panel of gun ownership by age and gender.

## Load data

```{r}
raw <-
  read_rds(
     here(
      path_od,
      "data",
      "clean",
      "gs-gen-pop.rds"
    )
  )
```


## Create panel of gun ownership 

```{r}
des <- svydesign(
  ids = ~1,        
  weights = ~weight,
  data = raw
)

est <-
  svyby(
    ~I(gun == "Yes" & 
         gender == "Male" & 
         age4 == "18-29" &
         grepl("White", racethnicity)
         ),
    ~year + state,
    des,
    svymean,
    keep.var = FALSE,
    vartype = c("se", "ci"),
      level = 0.95
    ) %>% 
    clean_names()
```



## State-year level

```{r}
long <-
  est %>%
  tibble() %>% 
  rename(gun = statistic_i_gun_yes_gender_male_age4_18_29_grepl_white_racethnicity_true) %>% 
  select(
    state, year, gun
  )
```

## Check missing states

```{r}
long %>% group_by(state) %>% filter(n() != 7) %>% tabyl(state)
```

AK and WY not present every year because of small sample sizes, so we drop.

```{r}
clean <-
  long %>% 
  group_by(state) %>% 
  filter(n() == 7) %>% 
  ungroup()
```

```{r}
n_distinct(clean$state)
```

## Save data

```{r}
write_rds(
  clean,
  here(
    path_od,
    "data",
    "clean",
    "gun-panel.rds"
  )
)
```