# Create panel

This chapter merges gun survey data with the implementation dates

```{r}
gun <-
  read_rds(
     here(
      path_od,
      "data",
      "clean",
      "gun-panel.rds"
    )
  )
```

```{r}
dates <-
  read_rds(
    here(
        path_od, 
        "data",
        "clean",
        "sportsbettingdates.rds"
    )
  )
```


## Merge

```{r}
merge <-
  gun %>% 
  inner_join(dates, by = "state")
```


## Define post treatment

```{r}
clean <-
  merge %>% 
  mutate(
    across(
      ends_with("date"),
      ~ year(.x),
      .names = "{str_replace_all(.col, 'date', 'year')}"
    ),
    across(
      ends_with("_year"),
      ~ case_when(
        !is.na(.x) ~ year >=.x,
        TRUE ~ F
      ) %>% as.numeric() %>% 
        factor(
          levels = 0:1,
          labels = c("Control", "Treatment")
        ),
      .names = "{str_replace_all(.col, 'year', 'post')}"
    ) 
  ) %>% 
  group_by(year) %>% 
  mutate(t = cur_group_id()) %>% 
  ungroup() %>% 
  mutate(
     across(
       ends_with("_year"),
      ~  case_when(
           is.na(.x) ~ 0,
           .x == year ~ t
      ),
      .names = "{str_replace_all(.col, 'year', 'g')}"
     )
  ) %>% 
  group_by(state)  %>% 
   mutate(
    across(ends_with("g"), ~ max(.x, na.rm = T)),
    stateid = cur_group_id()
  ) %>% 
  ungroup() %>% 
  mutate(
    across(
      ends_with("g"),
      ~ as.numeric(t >= .x & !is.na(.x)),
      .names = "{str_replace_all(.col, 'year', 'D')}"
    )
  )  
```

## Export data

```{r}
write_rds(
  clean,
  here(
    path_od,
    "data",
    "clean",
    "betting-panel.rds"
  )
)
```